version: "3.8"

services:
  bot:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./votes.db:/app/votes.db
      - ./bot.log:/app/bot.log
    environment:
      - TZ=Europe/Moscow